name: shopping_cart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  http: ^1.2.1
  dartz: ^0.10.1


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
